### ISSUE TITLE
Where's getAPI()?

### ISSUE THREAD

**Issue by RoboMWM** [mrsheepsheep/Tint-Health#3]
https://github.com/mrsheepsheep/Tint-Health/blob/b2bb11a34c69d73fd0fcd2a0a0dbc0d52a2286bb/src/main/java/fr/mrsheepsheep/tinthealth/THAPI.java#L18

But there is no getAPI :(

And since THAPI() is protected, I can't make a new instance of it either :(

**Comment by mrsheepsheep** [comment]
Aaah yup. My bad ! I wonder why I removed it in the last update... I'm gonna fix it tomorrow.
